name: toptop_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter
  cupertino_icons: ^1.0.2

  # auth using firebase
  firebase_auth: ^3.3.19
  # connect app to firebase
  firebase_core: ^1.17.1
  # sign in with google
  google_sign_in: ^5.3.2
  # firebase database
  cloud_firestore: ^3.1.17
  # storage video and image on firebase
  firebase_storage: ^10.2.17
  # enable app check
  firebase_app_check: ^0.0.6+13

  # using icon svg
  flutter_svg: ^1.0.3
  # lottie is a graphic Lib
  lottie: ^1.2.2
  # use font of GG
  google_fonts: ^2.3.2
  # icon lib
  font_awesome_flutter: ^10.1.0

  # format date
  intl: ^0.17.0
  # animation like button
  like_button: ^2.0.4
  # create top snackbar
  another_flushbar: ^1.10.28
  # create Pin code input field
  pinput: ^2.2.10

  # play video and keep it in cache dir
  cached_video_player:
    git:
      url: https://github.com/CK1412/flutter_cached_video_player.git
      ref: master
  # share video
  share_plus: ^4.0.4
  # pick image
  image_picker: ^0.8.5
  # compress video
  video_compress: ^3.1.0
  # keep images in the cache directory
  cached_network_image: ^3.2.0
  # save video to gallery
  gallery_saver: ^2.3.2

  # create a splash screen
  flutter_native_splash: ^2.1.6
  # state management
  flutter_riverpod: ^1.0.3
  # download files
  dio: ^4.0.6
  # save download file locally
  path_provider: ^2.0.10
  # open url
  url_launcher: ^6.1.2
  # store data as key-value (in this project is to save the view mode)
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/toptop-logo-dark.png"

flutter_native_splash:
  android: true
  ios: true
  color: "#FFFFFF"
  color_dark: "#121212"
  image: assets/logos/toptop-logo-light.png
  image_dark: assets/logos/toptop-logo-dark.png
  android_12:
    image: assets/logos/toptop-logo-light-android12.png
    image_dark: assets/logos/toptop-logo-dark-android12.png

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/lotties/
    - assets/logos/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
